import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Camera, ImageIcon, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
export const ImagePickerModal = ({ isVisible, onClose, onSelectCamera, onSelectGallery, title, }) => {
    const { t } = useTranslation();
    if (!isVisible)
        return null;
    return (_jsxs("div", { className: "fixed inset-0 z-[100] flex items-end justify-center sm:items-center", children: [_jsx("div", { className: "absolute inset-0 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200", onClick: onClose }), _jsxs("div", { className: "relative z-10 w-full max-w-sm mx-4 mb-4 sm:mb-0 bg-page dark:bg-page-dark rounded-2xl shadow-2xl animate-slide-up overflow-hidden border border-border dark:border-border-dark", children: [_jsxs("div", { className: "flex items-center justify-between p-4 border-b border-border dark:border-border-dark", children: [_jsx("h3", { className: "text-lg font-serif font-bold text-primary dark:text-primary-dark", children: title || t('imagePicker.title', 'Fotoğraf Seç') }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-surface dark:hover:bg-surface-dark rounded-full transition-colors", children: _jsx(X, { size: 20, className: "text-secondary" }) })] }), _jsxs("div", { className: "p-4 space-y-3", children: [_jsxs("button", { onClick: () => {
                                    onSelectCamera();
                                }, className: "w-full flex items-center gap-4 p-4 bg-surface dark:bg-surface-dark rounded-xl hover:bg-border/50 dark:hover:bg-border-dark/50 transition-all active:scale-[0.98] group", children: [_jsx("div", { className: "w-12 h-12 bg-accent/10 rounded-full flex items-center justify-center group-hover:bg-accent/20 transition-colors", children: _jsx(Camera, { size: 24, className: "text-accent" }) }), _jsxs("div", { className: "text-left", children: [_jsx("p", { className: "font-bold text-primary dark:text-primary-dark", children: t('imagePicker.camera', 'Kamera') }), _jsx("p", { className: "text-xs text-secondary dark:text-secondary-dark", children: t('imagePicker.cameraDesc', 'Yeni fotoğraf çek') })] })] }), _jsxs("button", { onClick: () => {
                                    onSelectGallery();
                                }, className: "w-full flex items-center gap-4 p-4 bg-surface dark:bg-surface-dark rounded-xl hover:bg-border/50 dark:hover:bg-border-dark/50 transition-all active:scale-[0.98] group", children: [_jsx("div", { className: "w-12 h-12 bg-accent/10 rounded-full flex items-center justify-center group-hover:bg-accent/20 transition-colors", children: _jsx(ImageIcon, { size: 24, className: "text-accent" }) }), _jsxs("div", { className: "text-left", children: [_jsx("p", { className: "font-bold text-primary dark:text-primary-dark", children: t('imagePicker.gallery', 'Galeri') }), _jsx("p", { className: "text-xs text-secondary dark:text-secondary-dark", children: t('imagePicker.galleryDesc', 'Galeriden seç') })] })] })] }), _jsx("div", { className: "p-4 pt-0", children: _jsx("button", { onClick: onClose, className: "w-full py-3 text-sm font-bold text-secondary hover:text-primary dark:hover:text-primary-dark transition-colors", children: t('imagePicker.cancel', 'Vazgeç') }) })] })] }));
};
export default ImagePickerModal;
