import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { X, Check, Minus } from 'lucide-react';
import { Button } from './Shared';
export const PremiumBenefitsModal = ({ onClose, onUpgrade, isPremium }) => {
    const benefits = [
        { name: "Gardırop Kapasitesi", free: "20 Parça", premium: "Sınırsız" },
        { name: "Günlük AI Analiz", free: "3 Adet", premium: "Sınırsız" },
        { name: "Kombin Önerileri", free: "Temel", premium: "Gelişmiş" },
        { name: "Stil İpuçları", free: "Standart", premium: "Kişiselleştirilmiş" },
        { name: "Reklamsız Deneyim", free: false, premium: true },
    ];
    return (_jsxs("div", { className: "fixed inset-0 z-[60] bg-white dark:bg-[#09090b] flex flex-col animate-in slide-in-from-bottom duration-300", children: [_jsxs("div", { className: "px-6 py-4 border-b border-gray-100 dark:border-gray-800 flex justify-between items-center sticky top-0 bg-white dark:bg-[#09090b]", children: [_jsx("h2", { className: "text-xl font-serif font-bold text-gray-900 dark:text-white", children: "\u00DCyelik \u00D6zellikleri" }), _jsx("button", { onClick: onClose, className: "p-2 bg-gray-50 dark:bg-gray-800 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors", children: _jsx(X, { size: 20, className: "text-gray-900 dark:text-white" }) })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-6", children: [_jsxs("div", { className: "bg-gray-50 dark:bg-[#1E1E1E] rounded-3xl p-1 mb-6 flex text-sm font-bold text-gray-500 dark:text-gray-400", children: [_jsx("div", { className: "flex-1 py-2 text-center", children: "\u00D6zellik" }), _jsx("div", { className: "w-20 py-2 text-center", children: "Free" }), _jsx("div", { className: "w-24 py-2 text-center text-lova-black dark:text-white", children: "Premium" })] }), _jsx("div", { className: "space-y-6", children: benefits.map((item, i) => (_jsxs("div", { className: "flex items-center text-sm border-b border-gray-50 dark:border-gray-800 pb-4 last:border-0", children: [_jsx("div", { className: "flex-1 font-medium text-gray-800 dark:text-gray-200", children: item.name }), _jsx("div", { className: "w-20 text-center text-gray-500 dark:text-gray-500 text-xs", children: typeof item.free === 'boolean' ? (item.free ? _jsx(Check, { size: 16, className: "mx-auto" }) : _jsx(Minus, { size: 16, className: "mx-auto" })) : item.free }), _jsx("div", { className: "w-24 text-center font-bold text-lova-nude text-xs", children: typeof item.premium === 'boolean' ? (item.premium ? _jsx(Check, { size: 16, className: "mx-auto" }) : _jsx(Minus, { size: 16, className: "mx-auto" })) : item.premium })] }, i))) }), !isPremium && onUpgrade && (_jsx("div", { className: "mt-8", children: _jsx(Button, { onClick: onUpgrade, children: "Premium'a Y\u00FCkselt" }) }))] })] }));
};
